from entities.endereco import Endereco
from entities.pessoal import Pessoal
from entities.academico import Academico
from entities.relatorio import Relatorio
from entities.resultado import Resultado
from entities.sessao import Sessao
from entities.perfil import Perfil
from entities.periodo import Periodo
from entities.disciplina import Disciplina
from entities.noticias import Noticias
from entities.disciplina import Disciplina 
from entities.horarios import Horarios
